apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofixfront-deployment
  labels:
    app: autofixfront-deployment
spec:
  selector:
    matchLabels:
      app: autofixfront-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: autofixfront-deployment
    spec:
      containers:
        - name: autofixfront-deployment
          image: algernonholmes/autofixfront
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: autofixfront-deployment
  labels:
    app: autofixfront-deployment
spec:
  selector:
    app: autofixfront-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer