apiVersion: apps/v1
kind: Deployment
metadata:
  name: repair-ms-deployment
  labels:
    app: repair-ms-deployment
spec:
  selector:
    matchLabels:
      app: repair-ms-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: repair-ms-deployment
    spec:
      containers:
        - name: repair-ms
          image: algernonholmes/repair-ms
          ports:
            - containerPort: 8092